# This workflow will build and test a .NET project

name: Build and test
run-name: ${{ github.actor }} is building and testing project 🚀

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore UI_Automation/UI_Automation.csproj
    - name: Build
      run: dotnet build UI_Automation/UI_Automation.csproj --no-restore
    - name: Test
      run: dotnet test UI_Automation/UI_Automation.csproj --no-build --verbosity normal
